# Generated by Django 5.0.3 on 2024-03-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscribedusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedusers',
            name='name',
        ),
    ]
